In [2]:
import duckdb
import pandas as pd

con = duckdb.connect('../Data/processed/project.duckdb')

In [3]:
con.execute("""
    SELECT COUNT(*) AS total_trades,
           COUNT(DISTINCT accountId) AS total_accounts,
           COUNT(DISTINCT campaignId) AS total_campaigns
    FROM trades
""").fetchdf()

   total_trades  total_accounts  total_campaigns
0         46520             502               34

a note here - in the provided datasets, we dont have campaigns 1-66 but 33-66 lolol

In [8]:
con.execute("""
    SELECT campaignId, COUNT(*) AS num_trades
    FROM trades
    GROUP BY campaignId
    ORDER BY campaignId
""").fetchdf()

   campaignId  num_trades
0          33         749
1          34         942
2          35        1030
3          36        1457
4          37        1432
5          38        1271
6          39        1180
7          40        1432
8          41        1227
9          42        1674
10         43        1404
11         44        1577
12         45        1255
13         46        1390
14         47         986
15         48        1469
16         49        1367
17         50        1171
18         51        1165
19         52         987
20         53        1063
21         54        1511
22         55        1222
23         56        1732
24         57        1256
25         58        1263
26         59        1490
27         60        1575
28         61        1573
29         62        1602
30         63        1715
31         64        1696
32         65        1746
33         66        1911